services:
  npm :
    container_name: npm
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
#      - /c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper # for Windows
        - ./:/epmsScrapper #For Mac and Linux
#        - /mnt/c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper


  scrapper:
    container_name: scrapper
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    volumes:
#      - /c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper # for Windows
      - ./:/epmsScrapper #For Mac and Linux
#      - /mnt/c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper
      - /epmsScrapper/node_modules
      - /root/.config/puppeteer:/root/.config/puppeteer

#    develop:
#      watch:
#        - action: sync
#          path: ./
#          target: /epmsScrapper
#          ignore:
#            - node_modules/
#        - action: rebuild
#          path: package.json
