services:
  npm :
    container_name: npm
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - /c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper # for Windows
  #      - ./:/epmsScrapper #For Mac and Linux

  apps:
    container_name: scrapper
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper # for Windows
#      - ./:/epmsScrapper #For Mac and Linux
      - /epmsScrapper/node_modules
#    develop:
#      watch:
#        - action: sync
#          path: ./
#          target: /epmsScrapper
#          ignore:
#            - node_modules/
#        - action: rebuild
#          path: package.json
