services:
  npm :
    container_name: npm
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
        - ./:/epmsScrapper #For Mac and Linux

  scrapper:
    container_name: scrapper
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
      target: ${NODE_ENV}
    volumes:
      - ./:/epmsScrapper #For Mac and Linux
      - /root/.config/puppeteer:/root/.config/puppeteer
      - ./local-data:/epmsScrapper/data
      - ${HOST_DATA_PATH}:/epmsScrapper/data

