services:
  npm :
    container_name: npm
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - /c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper # for Windows
#        - ./:/epmsScrapper #For Mac and Linux
#        - /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/a95a6f949cf57f9b5d993ec07629e84cc4163ef8b2d79f19ee99367163fe8658:/epmsScrapper


  scrapper:
    container_name: scrapper
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /c/Users/62220921/WebstormProjects/epmsScrapper:/epmsScrapper # for Windows
#      - ./:/epmsScrapper #For Mac and Linux
#      - /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/a95a6f949cf57f9b5d993ec07629e84cc4163ef8b2d79f19ee99367163fe8658:/epmsScrapper
      - /epmsScrapper/node_modules
#    develop:
#      watch:
#        - action: sync
#          path: ./
#          target: /epmsScrapper
#          ignore:
#            - node_modules/
#        - action: rebuild
#          path: package.json
